#!/bin/bash


/Users/addiemaggard/anaconda/bin/python /Users/addiemaggard/Documents/Belmont/Junior2/DataFileStructures/119/BSSweetwater.py

/Users/addiemaggard/anaconda/bin/python /Users/addiemaggard/Documents/Belmont/Junior2/DataFileStructures/119/SamAsh.py